import type { Metadata } from "next";
import Script from "next/script"
import "./globals.css";

export const metadata: Metadata = {
  title: "OTDM– Landing Page Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Script
          src="https://use.typekit.net/ldm8iso.js"
          strategy="beforeInteractive"
        />
        <Script id="adobe-font">
          {`try{Typekit.load({ async: true });}catch(e){}`}
        </Script>

        {children}
      </body>
    </html>
  );
}
